FROM nvidia/cuda:11.8.0-devel-ubuntu20.04

ENV DEBIAN_FRONTEND=noninteractive
ENV TZ=Asia/Hong_Kong
ENV CUDA_ARCH=89

RUN apt-get update && apt-get install -y \
    git build-essential cmake \
    libboost-program-options-dev libboost-filesystem-dev libboost-graph-dev \
    libboost-system-dev libboost-test-dev \
    libeigen3-dev libsuitesparse-dev libfreeimage-dev \
    libgoogle-glog-dev libgflags-dev \
    python3 python3-pip curl \
    libsqlite3-dev libgtk-3-dev libqt5opengl5-dev libceres-dev \
    libatlas-base-dev libmetis-dev \
    libcgal-dev libgmp-dev libmpfr-dev \
    libflann-dev libglew-dev \
    && rm -rf /var/lib/apt/lists/*

RUN git clone --branch 3.8 https://github.com/colmap/colmap.git /tmp/colmap \
    && cd /tmp/colmap \
    && mkdir build && cd build \
    && cmake .. -DCMAKE_BUILD_TYPE=Release -DCMAKE_CUDA_ARCHITECTURES="native" \
    && make -j4 \
    && make install \
    && rm -rf /tmp/colmap

COPY . /workspace/
WORKDIR /workspace

RUN pip3 install --upgrade pip && \
    pip3 install numpy opencv-python pillow

ENV PYTHONPATH="/workspace:/workspace/utils"

CMD ["python3", "dataset/colmap_manager_cloud.py"]